### ISSUE TITLE
Categories at the top are unclear (inappropriate, human...)

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/nutripatrol-frontend#45]
![image](https://github.com/openfoodfacts/nutripatrol-frontend/assets/562352/aa62556b-b0b3-48ca-a2ea-a05450642cf7)

1. When nothing is selected, is the list representing all categories by default? Shouldn't they be all highlighted in that case?

BTW, I think **we shouldn't be able to select more than one at a time**, because every task is very specific and if all categories are selected, we have to think about all cases for each product: is it inappropriate? is it a human? is it a cosmetic? is it something else (what)??

I think allowing to select more than one category is dangerous and will lead to click on "no problem" too often.

2. What is "inappropriate"? What is "other"? This is unclear. It should be explained somewhere. (A (?) aside?)

**Comment by Valimp** [comment]
@raphael0202 What do you think about this issue ?

**Comment by raphael0202** [comment]
That's fine for me to disable multi-select.
