### ISSUE TITLE
Add a thanks page after flagging products / images

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/nutripatrol-frontend#65]
### Problem
As we flag a product/image we are redirected to Nutripatrol home page.

This is not pleasant for a user who just flagged a product, and has no way to use the tool however.

### Proposed solution

Add a thanks page to thanks user for taking time to report, and explain that the team of volunteer will take care of it.

Also invite to contribute to the project and record how participation of everyone matters, with link to how to contribute.

Ideally we could also track a return location parameter and have a "continue navigation" button to return to where the user was before flagging.

**Comment by teolemon** [comment]
It would be nice to have an API route with number of contributions so that we can integrate it in the User Contributions screen of the app.
